# https://www.playframework.com/documentation/latest/Configuration

kafka {
	bootstrapServers = "localhost:9092"
	topic = "user-activity-events"
	clientId = "notification-server"
}

eventStream {
	ratePerSecond = 2000
	batchEveryMillis = 10
}
