services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq

    ports:
      # AMQP
      - "5672:5672"
      # Management UI
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

    volumes:
      - ./data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
