services:
  redis:
    image: redis:7-alpine
    container_name: redis

    ports:
      - "6379:6379"

    command: ["redis-server", "--appendonly", "yes"]

    volumes:
      - ./data:/data

    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
