# https://www.playframework.com/documentation/latest/Configuration

kafka {

	# Use the Docker-exposed host listener (see docker-compose.yaml)
	bootstrapServers = "localhost:29092"
	topic = "user-activity-events"
	clientId = "notification-server"
}

eventStream {

	ratePerSecond = 2000
	batchEveryMillis = 1000
}

# Play HTTP server
# Default Play port is 9000; use 7000 to avoid local conflicts.
play.server.http.port = 7000

slick.dbs.default.profile = "slick.jdbc.PostgresProfile$"

slick.dbs.default.db {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/notification_db"
  user = "postgres"
  password = "21125aaJV"
  connectionPool = "HikariCP"
  keepAliveConnection = true
}

# Flyway config
flyway.url = "jdbc:postgresql://localhost:5432/notification_db"
flyway.user = "postgres"
flyway.password = "21125aaJV"
flyway.locations = "classpath:db/migration"

#  Enable your module here
play.modules.enabled += "modules.DatabaseModule"